---
- include_tasks:
    file: internals/redhat_repositories-enable.yml

- include_tasks:
    file: internals/product-definition.yml

- include_tasks:
    file: internals/contentview-definition.yml

- include_tasks:
    file: internals/compositecontentview-definition.yml

- include_tasks:
    file: internals/lifecycleenvironment-definition.yml

- include_tasks:
    file: internals/activationkey-hostgroup-definition.yml
