---
- include_tasks:
    file: internals/redhat_repositories-enable.yml

- include_tasks:
    file: internals/product-definition.yml

- include_tasks:
    file: internals/repository-sync.yml

- include_tasks:
    file: internals/contentview-definition.yml

- include_tasks:
    file: internals/contentview-publish.yml

- include_tasks:
    file: internals/compositecontentview-definition.yml

- include_tasks:
    file: internals/compositecontentview-publish.yml

- include_tasks:
    file: internals/lifecycleenvironment-definition.yml

# promote contentview from Library->test
- include_tasks:
    file: internals/contentview-promote.yml
  vars:
    target_lce_name: "{{ test_lifecycleenvironment }}"
    source_lce_name: Library
  when:
    - test_lifecycleenvironment is defined
    - deploymentcontentview is defined

# promote contentview from test->prod
- include_tasks:
    file: internals/contentview-promote.yml
  vars:
    target_lce_name: "{{ prod_lifecycleenvironment }}"
    source_lce_name: "{{ test_lifecycleenvironment }}"
  when:
    - test_lifecycleenvironment is defined
    - prod_lifecycleenvironment is defined
    - deploymentcontentview is defined

- include_tasks:
    file: internals/activationkey-hostgroup-definition.yml
