---
- include_tasks:
    file: internals/facts-gathering.yml
    apply:
      tags:
        - always
  tags:
    - always

- include_tasks:
    file: internals/initial-define-infra.yml
    apply:
      tags:
        - define-infra
        - never
  tags:
    - define-infra
    - never

- include_tasks:
    file: internals/redhat_repositories-enable.yml
    apply:
      tags:
        - define-infra
        - change
        - never
  tags:
    - define-infra
    - change
    - never

- include_tasks:
    file: internals/product-definition.yml
    apply:
      tags:
        - define
        - change
        - never
  tags:
    - define
    - change
    - never

- include_tasks:
    file: internals/repository-sync.yml
    apply:
      tags:
        - define
        - sync
        - never
  tags:
    - define
    - sync
    - never

- include_tasks:
    file: internals/contentview-definition.yml
    apply:
      tags:
        - define
        - change
        - never
  tags:
    - define
    - change
    - never

- include_tasks:
    file: internals/contentview-publish.yml
    apply:
      tags:
        - define
        - publish
        - update-test
        - never
  tags:
    - define
    - change
    - never
    - update-test

- include_tasks:
    file: internals/compositecontentview-definition.yml
    apply:
      tags:
        - define
        - change
        - never
  tags:
    - define
    - change
    - never

- include_tasks:
    file: internals/compositecontentview-publish.yml
    apply:
      tags:
        - define
        - publish
        - update-test
        - never
  tags:
    - define
    - change
    - never
    - update-test

- include_tasks:
    file: internals/lifecycleenvironment-definition.yml
    apply:
      tags:
        - define
        - change
        - never
  tags:
    - define
    - change
    - never

# promote contentview from Library->test
- include_tasks:
    file: internals/contentview-promote.yml
    apply:
      tags:
        - define
        - change
        - update-test
        - never
  vars:
    target_lce_name: "{{ g_test_lifecycleenvironment }}"
    source_lce_name: Library
  when: g_test_lifecycleenvironment_defined
  tags:
    - define
    - update-test
    - never

# promote contentview from test->prod
- include_tasks:
    file: internals/promote-contentview.yml
    apply:
      tags:
        - define
        - change
        - update-prod
        - never
  vars:
    target_lce_name: "{{ g_prod_lifecycleenvironment }}"
    source_lce_name: "{{ g_test_lifecycleenvironment }}"
  when: g_test_lifecycleenvironment_defined and g_prod_lifecycleenvironment_defined
  tags:
    - define
    - update-prod
    - never

- include_tasks:
    file: internals/activationkey-hostgroup-definition.yml
    apply:
      tags:
        - define
        - change
        - never
  tags:
    - define
    - change
    - never

## All provisionning tasks are finished, will start defining the decommissioning tasks

- include_tasks:
    file: internals/activationkey-hostgroups-deprovision.yml
    apply:
      tags:
        - never
        - deprovision
  tags:
    - never
    - deprovision

- include_tasks:
    file: internals/lifecycleenvironment-deprovision.yml
    apply:
      tags:
        - never
        - deprovision
  tags:
  - never
  - deprovision

- include_tasks:
    file: internals/compositecontentview-deprovision.yml
    apply:
      tags:
        - never
        - deprovision
  tags:
    - never
    - deprovision

- include_tasks:
    file: internals/contentview-deprovision.yml
    apply:
      tags:
        - never
        - deprovision
  tags:
  - never
  - deprovision

- include_tasks:
    file: internals/products-deprovision.yml
    apply:
      tags:
        - never
        - deprovision
  tags:
    - never
    - deprovision
