---
# promote contentview from test->prod
- include_tasks:
    file: internals/contentview-promote.yml
  vars:
    target_lce_name: "{{ prod_lifecycleenvironment }}"
    source_lce_name: "{{ test_lifecycleenvironment }}"
  when:
    - test_lifecycleenvironment is defined
    - prod_lifecycleenvironment is defined
    - deploymentcontentview is defined

- include_tasks:
    file: internals/wait-for-capsule-sync.yml
  when: wait_capsule_sync
