---
- include_tasks:
    file: internals/contentview-publish.yml

- include_tasks:
    file: internals/compositecontentview-publish.yml

# promote contentview from Library->test
- include_tasks:
    file: internals/contentview-promote.yml
  vars:
    target_lce_name: "{{ test_lifecycleenvironment }}"
    source_lce_name: Library
  when:
    - test_lifecycleenvironment is defined
    - deploymentcontentview is defined

- include_tasks:
    file: internals/wait-for-capsule-sync.yml
  when: wait_capsule_sync
