- name: "Deprovision hostgroup for production"
  theforeman.foreman.hostgroup:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ prod_hostgroup }}"
    organization: "{{ satellite_organization }}"
    organizations:
    - "{{ satellite_organization }}"
    domain: "{{ prod_domain | default(omit) }}"
    architecture: "{{ prod_architecture | default(omit) }}"
    ptable: "{{ prod_partition_table | default(omit) }}"
    operatingsystem: "{{ prod_operatingsystem | default(omit) }}"
    medium: "{{ prod_provision_installation_media | default(omit) }}"
    content_source: "{{ prod_foreman_capsule | default(omit) }}"
    lifecycle_environment: "{{ prod_lifecycleenvironment }}"
    parent: "{{ prod_hostgroup_parent | default(omit) }}"
    pxe_loader: "{{ prod_pxe_loader | default(omit) }}"
    locations: "{{ locations.keys() | list }}"
    parameters:
    - name: "kt_activation_keys"
      value: "{{ prod_activationkey }}"
    content_view: "{{ deploymentcontentview }}"
    state: absent
  when:
    - prod_lifecycleenvironment is defined
    - deploymentcontentview is defined
    - prod_activationkey is defined
    - prod_hostgroup is defined
  ignore_errors: yes

- name: "Deprovision Activation Key for production"
  theforeman.foreman.activation_key:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ prod_activationkey }}"
    content_view: "{{ deploymentcontentview }}"
    lifecycle_environment: "{{ prod_lifecycleenvironment }}"
    subscriptions: "{{ subscriptions | default(omit) }}"
    content_overrides: "{{ contentoverrides | default(omit) }}"
    auto_attach: True
    organization: "{{ satellite_organization }}"
    state: absent
  ignore_errors: yes
  when:
    - prod_lifecycleenvironment is defined
    - deploymentcontentview is defined
    - prod_activationkey is defined

- name: "Deprovision hostgroup for test"
  theforeman.foreman.hostgroup:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ test_hostgroup }}"
    organization: "{{ satellite_organization }}"
    organizations:
    - "{{ satellite_organization }}"
    domain: "{{ test_domain | default(omit) }}"
    architecture: "{{ test_architecture | default(omit) }}"
    ptable: "{{ test_partition_table | default(omit) }}"
    operatingsystem: "{{ test_operatingsystem | default(omit) }}"
    medium: "{{ test_provision_installation_media | default(omit) }}"
    content_source: "{{ test_foreman_capsule | default(omit) }}"
    lifecycle_environment: "{{ test_lifecycleenvironment }}"
    parent: "{{ test_hostgroup_parent | default(omit) }}"
    pxe_loader: "{{ test_pxe_loader | default(omit) }}"
    locations: "{{ locations.keys() | list }}"
    parameters:
    - name: "kt_activation_keys"
      value: "{{ test_activationkey }}"
    content_view: "{{ deploymentcontentview }}"
    state: absent
  when:
    - test_lifecycleenvironment is defined
    - deploymentcontentview is defined
    - test_activationkey is defined
    - test_hostgroup is defined
  ignore_errors: yes

- name: "Delete Activation Key for test"
  theforeman.foreman.activation_key:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ test_activationkey }}"
    content_view: "{{ deploymentcontentview }}"
    lifecycle_environment: "{{ test_lifecycleenvironment }}"
    subscriptions: "{{ subscriptions | default(omit) }}"
    content_overrides: "{{ contentoverrides | default(omit) }}"
    auto_attach: True
    organization: "{{ satellite_organization }}"
    state: absent
  ignore_errors: yes
  when:
    - test_lifecycleenvironment is defined
    - deploymentcontentview is defined
    - test_activationkey is defined
