- name: "Delete ContentViews"
  theforeman.foreman.content_view:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ item.name }}"
    organization: "{{ satellite_organization }}"
    state: absent
  ignore_errors: yes
  with_items: "{{ contentviews | default([]) }}"
