- name: "Start Publishing ContentViews"
  theforeman.foreman.content_view_version:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    content_view: "{{ item.name }}"
    organization: "{{ satellite_organization }}"
  with_items: "{{ contentviews | default([]) }}"
  async: 999999
  poll: 0
  register: g_contentview_publish_sleeper

- name: 'Wait until all ContentViews are published'
  async_status:
    jid: "{{ contentview_publish_sleeper_item.ansible_job_id }}"
  loop: "{{ g_contentview_publish_sleeper.results }}"
  loop_control:
    loop_var: contentview_publish_sleeper_item
  when: contentview_publish_sleeper_item.ansible_job_id is defined  # Skip items that were skipped in the previous task
  register: async_job_result2
  until: async_job_result2.finished
  retries: 9999
  delay: 10
