- name: 'Define ContentViews'
  theforeman.foreman.content_view:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ item.name }}"
    organization: "{{ satellite_organization }}"
    repositories: "{{ item.repositories | default([]) | map('camptocamp.satellite.whitelist_contentview_attr') | list }}"
  with_items: "{{ contentviews | default([]) }}"

- name: 'Define ContentView Filters'
  include_tasks:
    file: internals/snippets/define_filter_contentview.yml
  with_subelements:
  - "{{ contentviews | default({}) }}"
  - repositories
  - skip_missing: True
  loop_control:
    loop_var: contentview_repo
