---
- name: Collect facts about Activation Keys / Hostgroups / LifeCycle Environments
  block:
  - set_fact:
      g_test_lifecycleenvironment_is_groupvar: "{{ (groups['test'] | default([]) | length>0) and ('lifecycleenvironment' in hostvars[groups['test'][0]]) }}"
      g_prod_lifecycleenvironment_is_groupvar: "{{ (groups['prod'] | default([]) | length>0) and ('lifecycleenvironment' in hostvars[groups['prod'][0]]) }}"

      g_test_activationkey_is_groupvar: "{{ (groups['test'] | default([]) | length>0) and ('activationkey' in hostvars[groups['test'][0]]) }}"
      g_prod_activationkey_is_groupvar: "{{ (groups['prod'] | default([]) | length>0) and ('activationkey' in hostvars[groups['prod'][0]]) }}"

      g_test_hostgroup_is_groupvar: "{{ (groups['test'] | default([]) | length>0) and ('hostgroup' in hostvars[groups['test'][0]]) }}"
      g_prod_hostgroup_is_groupvar: "{{ (groups['prod'] | default([]) | length>0) and ('hostgroup' in hostvars[groups['prod'][0]]) }}"

      g_test_domain_is_groupvar: "{{ (groups['test'] | default([]) | length>0) and ( 'domain' in hostvars[groups['test'][0]] ) }}"
      g_prod_domain_is_groupvar: "{{ (groups['prod'] | default([]) | length>0) and ( 'domain' in hostvars[groups['prod'][0]] ) }}"

      g_test_architecture_is_groupvar: "{{ (groups['test'] | default([]) | length>0) and ( 'architecture' in hostvars[groups['test'][0]] ) }}"
      g_prod_architecture_is_groupvar: "{{ (groups['prod'] | default([]) | length>0) and ( 'architecture' in hostvars[groups['prod'][0]] ) }}"

      g_test_partition_table_is_groupvar: "{{ (groups['test'] | default([]) | length>0) and ( 'partition_table' in hostvars[groups['test'][0]] ) }}"
      g_prod_partition_table_is_groupvar: "{{ (groups['prod'] | default([]) | length>0) and ( 'partition_table' in hostvars[groups['prod'][0]] ) }}"

      g_test_operatingsystem_is_groupvar: "{{ (groups['test'] | default([]) | length>0) and ( 'operatingsystem' in hostvars[groups['test'][0]] ) }}"
      g_prod_operatingsystem_is_groupvar: "{{ (groups['prod'] | default([]) | length>0) and ( 'operatingsystem' in hostvars[groups['prod'][0]] ) }}"

      g_test_medium_is_groupvar: "{{ (groups['test'] | default([]) | length>0) and ( 'medium' in hostvars[groups['test'][0]] ) }}"
      g_prod_medium_is_groupvar: "{{ (groups['prod'] | default([]) | length>0) and ( 'medium' in hostvars[groups['prod'][0]] ) }}"

      g_test_foreman_capsule_is_groupvar: "{{ (groups['test'] | default([]) | length>0) and ( 'foreman_capsule' in hostvars[groups['test'][0]] ) }}"
      g_prod_foreman_capsule_is_groupvar: "{{ (groups['prod'] | default([]) | length>0) and ( 'foreman_capsule' in hostvars[groups['prod'][0]] ) }}"

      g_test_hostgroup_parent_is_groupvar: "{{ (groups['test'] | default([]) | length>0) and ( 'hostgroup_parent' in hostvars[groups['test'][0]] ) }}"
      g_prod_hostgroup_parent_is_groupvar: "{{ (groups['prod'] | default([]) | length>0) and ( 'hostgroup_parent' in hostvars[groups['prod'][0]] ) }}"

      g_test_pxe_loader_is_groupvar: "{{ (groups['test'] | default([]) | length>0) and ( 'pxe_loader' in hostvars[groups['test'][0]] ) }}"
      g_prod_pxe_loader_is_groupvar: "{{ (groups['prod'] | default([]) | length>0) and ( 'pxe_loader' in hostvars[groups['prod'][0]] ) }}"

  - set_fact:
      g_test_lifecycleenvironment_is_globalvar: "{{ test_lifecycleenvironment is defined }}"
      g_prod_lifecycleenvironment_is_globalvar: "{{ prod_lifecycleenvironment is defined }}"

      g_test_activationkey_is_globalvar: "{{ test_activationkey is defined }}"
      g_prod_activationkey_is_globalvar: "{{ prod_activationkey is defined }}"

      g_test_hostgroup_is_globalvar: "{{ test_hostgroup is defined }}"
      g_prod_hostgroup_is_globalvar: "{{ prod_hostgroup is defined }}"

  - set_fact:
      g_test_lifecycleenvironment_defined: "{{ ( g_test_lifecycleenvironment_is_groupvar or g_test_lifecycleenvironment_is_globalvar ) and deploymentcontentview is defined }}"
      g_prod_lifecycleenvironment_defined: "{{ ( g_prod_lifecycleenvironment_is_groupvar or g_prod_lifecycleenvironment_is_globalvar ) and deploymentcontentview is defined }}"

      g_test_activationkey_defined: "{{ g_test_activationkey_is_groupvar or g_test_activationkey_is_globalvar }}"
      g_prod_activationkey_defined: "{{ g_prod_activationkey_is_groupvar or g_prod_activationkey_is_globalvar }}"

      g_test_hostgroup_defined: "{{ g_test_hostgroup_is_groupvar or g_test_hostgroup_is_globalvar }}"
      g_prod_hostgroup_defined: "{{ g_prod_hostgroup_is_groupvar or g_prod_hostgroup_is_globalvar }}"

  - set_fact:
      g_test_lifecycleenvironment: "{{ hostvars[groups['test'][0]]['lifecycleenvironment'] if g_test_lifecycleenvironment_is_groupvar else test_lifecycleenvironment }}"
    when: g_test_lifecycleenvironment_defined

  - set_fact:
      g_prod_lifecycleenvironment: "{{ hostvars[groups['prod'][0]]['lifecycleenvironment'] if g_prod_lifecycleenvironment_is_groupvar else prod_lifecycleenvironment }}"
    when: g_prod_lifecycleenvironment_defined

  - set_fact:
      g_test_activationkey: "{{ hostvars[groups['test'][0]]['activationkey'] if g_test_activationkey_is_groupvar else test_activationkey }}"
    when: g_test_activationkey_defined

  - set_fact:
      g_prod_activationkey: "{{ hostvars[groups['prod'][0]]['activationkey'] if g_prod_activationkey_is_groupvar else prod_activationkey }}"
    when: g_prod_activationkey_defined

  - set_fact:
      g_test_hostgroup: "{{ hostvars[groups['test'][0]]['hostgroup'] if g_test_hostgroup_is_groupvar else test_hostgroup }}"
    when: g_test_hostgroup_defined

  - set_fact:
      g_prod_hostgroup: "{{ hostvars[groups['prod'][0]]['hostgroup'] if g_prod_hostgroup_is_groupvar else prod_hostgroup }}"
    when: g_prod_hostgroup_defined
