- name: Define Organizations
  theforeman.foreman.organization:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ item }}"
  with_items: "{{ organizations | default([]) }}"

- name: Define domains
  theforeman.foreman.domain:
    name: "{{ item.key }}"
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    organizations: "{{ item.value.organizations | default(organizations) }}"
    locations: "{{ item.value.locations | default(locations.keys()) | list }}"
    description: "{{ item.value.description }}"
  with_dict: "{{ domains | default([]) }}"

- name: Setup Authentication Source
  theforeman.foreman.auth_source_ldap:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: " {{ item.name }} "
    host: "{{ item.host }}"
    port: "{{ item.port }}"
    tls: "{{ item.tls }}"
    organizations: "{{ item.value.organizations | default(organizations) }}"
    locations: "{{ item.value.locations | default(locations.keys()) }}"
    server_type: "{{ item.server_type }}"
    usergroup_sync: "{{ item.usergroup_sync }}"
    account: "{{ item.account }}"
    account_password: "{{ ad_auth_pwd }}"
    base_dn: "{{ item.base_dn }}"
    groups_base: "{{ item.groups_base }}"
    ldap_filter: "{{ item.ldap_filter }}"
    attr_login: "{{ item.attr_login }}"
    attr_firstname: "{{ item.attr_firstname }}"
    attr_lastname: "{{ item.attr_lastname }}"
    attr_mail: "{{ item.attr_mail }}"
    onthefly_register: "{{ item.onthefly_register }}"
    state: "{{ item.state }}"
  with_items: "{{ ad_auth | default([]) }}"

- name: Define User Group admin
  theforeman.foreman.usergroup:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ item.name }}"
    admin: "{{ item.admin }}"
  with_items: "{{ usergroup | default([]) }}"

- name: Define external user group
  theforeman.foreman.external_usergroup:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ item.external_usergroup_name }}"
    auth_source: "{{ item.auth_source }}"
    usergroup: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ usergroup | default([]) }}"

- name: Define partition tables
  theforeman.foreman.partition_table:
    name: "{{ item.key }}"
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    layout: "{{ item.value.partition_table }}"
    locations: "{{ item.value.locations | default(locations.keys()) | list }}"
    organizations: "{{ item.value.organizations | default(organizations) }}"
    os_family: "{{ item.value.os_family }}"
    locked: false
  with_dict: "{{ partition_tables | default({}) }}"

- include_tasks:
    file: internals/snippets/define_provisining_templates.yml
  with_items: "{{ provisioning_templates | default([])}}"
  loop_control:
    loop_var: template_source

- name: Define Installation Media
  theforeman.foreman.installation_medium:
    name: "{{ item.key }}"
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    locations: "{{ item.value.locations | default( locations.keys() ) | list }}"
    organizations: "{{ item.value.organizations | default( organizations ) }}"
    os_family: "{{ item.value.os_family }}"
    path: "{{ item.value.path }}"
    state: "{{ item.value.state  | default('present') }}"
  with_dict: "{{ installation_media | default({}) }}"

- name: "Create Operating Systems (provide default info)"
  theforeman.foreman.operatingsystem:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    family: "{{ item.family }}"
    architectures: "{{ item.architectures }}"
    media: "{{ item.media | default(omit) }}"
    ptables: "{{ item.ptables }}"
    password_hash: "{{ item.password_hash }}"
    provisioning_templates: "{{ item.provisioning_templates }}"
    major: "{{ item.major }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ operating_systems | default([]) }}"

- include_tasks:
    file: internals/snippets/define_os_template_association.yml
  with_items:
  - "{{ operating_systems | default([]) }}"
  loop_control:
    loop_var: operating_system

- name: Define subnets
  theforeman.foreman.subnet:
    name: "{{ item.key }}"
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    network: "{{ item.value.network }}"
    cidr: "{{ item.value.cidr }}"
    mask: "{{ item.value.mask }}"
    gateway: "{{ item.value.gateway }}"
    domains: "{{ item.value.domains | default( domains.keys() ) | list }}"
    organizations: "{{ item.value.organizations | default( organizations ) }}"
    dns_primary: "{{ item.value.dns_primary | default(dns_primary) }}"
    dns_secondary: "{{ item.value.dns_secondary | default(dns_secondary) }}"
    boot_mode: "{{ item.value.boot_mode | default(boot_mode) }}"
    locations: "{{ item.value.locations | default(locations.keys()) | list }}"
    ipam: "{{ item.value.ipam | default(ipam) }}"
  with_dict: "{{ subnets | default({}) }}"

- name: "Define infrastructure-wide hostgroups"
  theforeman.foreman.hostgroup:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"

    name: "{{ item['name'] }}"
    organization: "{{ item['satellite_organization'] }}"
    organizations:
    - "{{ item['satellite_organization'] }}"
    domain: "{{ item['domain'] }}"
    architecture: "{{ item['architecture'] }}"
    ptable: "{{ item['partition_table'] }}"
    operatingsystem: "{{ item['operatingsystem'] }}"
    medium: "{{ item['provision_installation_media'] | default(omit) }}"
    content_source: "{{ item['foreman_capsule'] }}"
    pxe_loader: "{{ item['pxe_loader'] | default(omit) }}"
    locations: "{{ item['locations'] | default(locations.keys()) | list }}"
    parameters:
    - name: "c2c_puppet_disable_revocation"
      value: "{{ item['c2c_puppet_disable_revocation'] }}"
      parameter_type: "boolean"
    - name: "c2c_puppet_shared_key"
      value: "{{ item['c2c_puppet_shared_key'] }}"
    - name: "puppetca_port"
      value: "{{ item['puppetca_port'] }}"
    - name: "puppet_ca_server"
      value: "{{ item['puppet_ca_server'] }}"
    - name: "puppetmaster"
      value: "{{ item['puppetmaster'] }}"
    - name: "puppetmaster_port"
      value: "{{ item['puppetmaster_port'] }}"
    - name: "c2c_puppet_env"
      value: "{{ item['puppet_environment'] }}"
    - name: "capsules_load_balancer_fqdn"
      value: "{{ item['capsules_load_balancer_fqdn'] }}"
    - name: "use_ntp"
      value: "{{ item['use_ntp'] }}"
      parameter_type: "boolean"
    - name: "redhat_install_agent"
      value: "{{ item['redhat_install_agent'] }}"
      parameter_type: "boolean"
    - name: "redhat_install_host_tools"
      value: "{{ item['redhat_install_host_tools'] }}"
      parameter_type: "boolean"
    - name: "redhat_install_host_tracer_tools"
      value: "{{ item['redhat_install_host_tracer_tools'] }}"
      parameter_type: "boolean"
    - name: "host_registration_insights"
      value: "{{ item['host_registration_insights'] }}"
      parameter_type: "boolean"
  with_items: "{{ infra_hostgroups | default([]) }}"
