- name: 'Defining Lifecycle Environment for test'
  theforeman.foreman.lifecycle_environment:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ g_test_lifecycleenvironment }}"
    prior: Library
    organization: "{{ satellite_organization }}"
    label: "{{ g_test_lifecycleenvironment }}"
  when: g_test_lifecycleenvironment_defined

- name: 'Defining Lifecycle Environment for prod'
  theforeman.foreman.lifecycle_environment:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ g_prod_lifecycleenvironment }}"
    prior: "{{ g_test_lifecycleenvironment }}"
    organization: "{{ satellite_organization }}"
    label: "{{ g_prod_lifecycleenvironment }}"
  when: g_test_lifecycleenvironment_defined and g_prod_lifecycleenvironment_defined
