- name: 'Delete Lifecycle Environment for prod'
  theforeman.foreman.lifecycle_environment:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ prod_lifecycleenvironment }}"
    organization: "{{ satellite_organization }}"
    state: "absent"
  ignore_errors: yes
  when:
    - test_lifecycleenvironment is defined
    - prod_lifecycleenvironment is defined
    - deploymentcontentview is defined

- name: 'Delete Lifecycle Environment for test'
  theforeman.foreman.lifecycle_environment:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ test_lifecycleenvironment }}"
    organization: "{{ satellite_organization }}"
    state: "absent"
  ignore_errors: yes
  when:
    - test_lifecycleenvironment is defined
    - deploymentcontentview is defined
