- name: 'Init Repository list'
  set_fact:
    repository_list_to_sync: []
  tags:
  - never
  - sync
  - define

- name: Collect Repositories used in ContentViews
  set_fact:
    repository_list_to_sync: "{{ repository_list_to_sync + item.repositories }}"
  with_items: "{{ contentviews | default([]) }}"

- name: 'Start sync of Repositories'
  theforeman.foreman.repository_sync:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pwd }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    product: "{{ item.product }}"
    repository:  "{{ item.name }}"
    organization: "{{ satellite_organization }}"
  when: item.synchronize | default(True)
  loop: "{{ repository_list_to_sync | default([]) | list }}"
  loop_control:
    pause: 3
  async: 999999
  poll: 0
  register: g_repo_sync_sleeper

- name: 'Wait until all Syncs have finished'
  async_status:
    jid: "{{ repo_sync_sleeper_item.ansible_job_id }}"
  loop: "{{ g_repo_sync_sleeper.results }}"
  loop_control:
    loop_var: repo_sync_sleeper_item
  when: repo_sync_sleeper_item.ansible_job_id is defined # Skip items that were skipped in the previous task
  register: async_job_result
  until: async_job_result.finished
  retries: 9999
  delay: 10

